### ISSUE TITLE
Editable section of user profile page for links to projects, etc. 

### ISSUE THREAD

**Issue by megamattron** [larvalabs/pullup#225]
Probably done with markdown.

**Comment by rickhanlonii** [comment]
@megamattron are you thinking a freeform text field like stackoverflow? Or something more structured?

![](http://dp.hanlon.io/022u1D10301p/Image%202016-03-02%20at%205.39.25%20PM.png)

**Comment by megamattron** [comment]
I was thinking free form, maybe markdown.
