### ISSUE TITLE
Have a way to see who upvoted a story

### ISSUE THREAD

**Issue by pents90** [larvalabs/pullup#260]
Seems like there is no need to keep it anonymous, and it would be nice to know who digs something.

**Comment by rickhanlonii** [comment]
I dig this idea, especially because it's departure from other sites. It also may be a natural way to encourage thoughtful voting.

> I could see this turning into a more personalized news site.

Really like this idea @chall8908. I'd love to follow/view only links PG or tptacek has upvoted on HN, for example.
