### ISSUE TITLE
Track Created Dates

### ISSUE THREAD

**Issue by josephwegner** [larvalabs/pullup#279]
Right now we aren't tracking created dates for votes or users..  We don't have any specific need for them yet, but I have some features spinning in my head that will require both of them...

created_date on user should be the same thing as the registration date
created_date on a vote should be pretty obvious...

What do we do about historical data here? Leave it blank? Set it to the push date? Does anyone have any opinions about how we should do database migrations?

**Comment by rickhanlonii** [comment]
I think that makes sense @treygriffith. Going to close for now, but we can re-open if required.
