### ISSUE TITLE
Better Error Logging

### ISSUE THREAD

**Issue by josephwegner** [larvalabs/pullup#282]
See: https://github.com/larvalabs/pullup/blob/master/app.js#L149

Right now we are logging the request and the error. Unfortunately, the request is just outputting as an abstract JS object. We should at least output the request URL here.

Right now the logs look like:
```
77 <13>1 2014-03-04T19:51:59.225602+00:00 host app web.1 - req: [object Object]
79 <13>1 2014-03-04T19:51:59.225602+00:00 host app web.1 - error:Error: Forbidden
```

**Comment by genetique-techno** [comment]
I'd like to take a crack at this.  Would you prefer I fork or make an issue branch to get started?

**Comment by megamattron** [comment]
@genetique-techno Usually a pull request is best for these things. I should warn you the site has been pretty quiet for the past while, you're welcome to get into the code if you feel like it though!

**Comment by genetique-techno** [comment]
@megamattron This will be my first open source PR, so I'm happy to work on something even if it's been quiet!

**Comment by rickhanlonii** [comment]
@genetique-techno any luck?

**Comment by genetique-techno** [comment]
@rickhanlonii yes but this might not have been closed because I didn't add myself to the userlist...got busy with work
#381

**Comment by rickhanlonii** [comment]
Nice! Sorry I missed that. If you add a PR to add yourself, I'll happily merge.
