### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by josephwegner** [larvalabs/pullup#294]
Right now the about page says things like:

**What features should I add?**
*Right now we could use things like commenting, voting, bookmarklet and so on. If you’re ambitious maybe private messaging? Almost anything, as even this page sucks, for example.*

Well, we already have those features, so clearly the about page is out of date.  Update it with some more accurate information.

**Comment by rickhanlonii** [comment]
Updated the copy and added a link to the beginner issues in #383.
