### ISSUE TITLE
Idea: Contribution Log

### ISSUE THREAD

**Issue by willurd** [larvalabs/pullup#305]
A log of all of your contributions to pullup.io and the Pullup community.

Your log starts with your initial pull request and join date. When you submit another pull request that is merged, that is added to your log. If you help a new user submit their first pull request, that is added to your log. Any verifiable contribution to the *community* or *code* goes into your log.

What's not in your log: news submissions, comments, upvotes, etc.

**Comment by rickhanlonii** [comment]
I think to start we can just query the github API for pull requests by author and show that list on each user's page.
