### ISSUE TITLE
Add Site Analytics

### ISSUE THREAD

**Issue by josephwegner** [larvalabs/pullup#316]
The tricky part here is that we need to do analytics in such a way that community members can see it..  I'm in favor of just making it a members only page, but that can be open for discussion.

Possible analytics providers:
- [Keen.IO](https://keen.io/)
- [Google Analytics](http://www.google.com/analytics/)
- [MixPanel](https://mixpanel.com/)

I vote in favor of Keen, because they make it super easy to create public dashboards, but that is also open for discussion.

**Comment by rickhanlonii** [comment]
@megamattron mind creating the @larvalabs account and adding me as a member?
