### ISSUE TITLE
Ansible Vagrant NodeJS Mongo Grunt Express Julia... not too clear where to start reading

### ISSUE THREAD

**Issue by LeadingQuestion** [larvalabs/pullup#326]
So... I am enjoying this adventure so far, but I am wondering how many more hours it will take me. I can read ECMAScript-ese and CSS and HTML, know pretty much how HTTP works and DNS, and am ready to learn everything else I need to to join you, but I can certainly say it is unclear from even the literate-newbie point of view where to start reading.

As of now (five hours in.... I got sidetracked and learned how to build what I want, instead of where to put it to have it get called).... I'm reading Julia documentation and somehow got into Travis.CI and.... too many interesting things to learn.

Also:  I believe that a number of mentioned issues (like deleting the gender check etc.) are mentioned here and there on Issues here on github or on the actual site, that have actually been fixed and are still listed as open. I felt like I got baited into looking around the source tree for where I might help, and hit dead ends.

So I think I'll try something simpler to find but more ambitious.... something I can suggest might be added to every page to help onboard people like me. Which therefore requires knowing how a page gets served.

I guess I'll keep it up, starting on reading how NodeJS serves pages, routes URLs and uses its DB and template-application steps in the serve-a-response pipeline after it hears the "GET [URI]".

I also guess, never having done any development that wasn't local, that I have an even more basic question: When using github for a project like this (a SITE, with its stack, not just a programing language, resource files, or libraries or code snippets) does one usually commit every single include-required config file, and a build and a deploy script somewhere? I'm wondering if all the NodeJS startup files and environment settings will be clear enough for me, so that once I understand NodeJS as well as I used to know Apache, say, I'll know what's what RE how it's configured to serve pullup.

As a suggestion: tell people on the how to contribute page where to start reading (e.g. 
  https://github.com/larvalabs/pullup/blob/master/hackathon-starter-readme.md )

I feel like I did coming from a procedural background, learning my first OO framework (AWT) after reading OO architecture books that all somehow forgot to mention that, when reading somebody else's framework codebase you start with the constructor of the Application object, or it's equivalent, which might be somewhere close to a "main" function.... and then keep reading from there.

**Just to be clear: the current hurdle to entry for code-capable n00bs is:** figure out how all components of the stack and framework interact, find the places to change for your improvement, change them, *then* add your name and request a pull. If I had a single HTML file, a single CSS, and just say JQuery and a pullupSpecifics.js file to read, I could build you a rocketship, comparatively. For now though, I'm off to read.

I'm leaving this here because I've seen the comments and several of you are vocal about wanting this to be more inviting to people who basically are at the "know JS" level.

I saw several "just make a github account and get started" responses to people looking to start their webdev self-education on HackerNews, and I just got started. I was loving codepen and -fiddle sites as ways to code without setup, but learning to develop requires learning default chunck of common stacks, or at lease one set that you choose yourself.

The pulllup entry on ...on.... doerhub? Or on github itself? was enough of an incentive to finally step up and get started. The "pull to join" idea as a social experiment to find out what sort of community would accrete is what drew me, so I am on that side of the debate.

Ideally, though, I'd have build it on a very minimal stack. And written an architecture onboarding doc.

Thanks. 
2cents from a future member

**Comment by rickhanlonii** [comment]
Thanks for the thoughts @LeadingQuestion, it's great to meet you (sorry for the 2 year delay). 

Since this issue we've added a `beginner` label for issues that _should_ contain issues that are easy to solve in the code base. An experienced contributor should be able to outline the solution to these off the top of their head, so ping'ing people in the chat or on issues is the best way to get help.

If you need any guidance, don't hesitate to ask!
