### ISSUE TITLE
Can't Post new Chat Messages

### ISSUE THREAD

**Issue by treygriffith** [larvalabs/pullup#333]
Gitter must have changed something, as I can't seem to find the box to submit new messages on our /chat page.

**Comment by fsask** [comment]
Logged in via Github, but Chat item at bottom of page is greyed out. This sounds really ridiculous, but I can't seem to figure out how to ADD my comments to a conversation!

**Comment by rickhanlonii** [comment]
@fsask I think it's a CSS issue, please fix and add your name to [`userlist.js`](https://github.com/djstearns/pullup/blob/master/config/userlist.js). 

You can also go directly to the Gitter chat page [here](https://gitter.im/larvalabs/pullup).

**Comment by rickhanlonii** [comment]
Gitter appears to have fixed the issue by adding a login button:

![](http://dp.hanlon.io/2R2F350N0P3b/Image%202016-03-03%20at%2012.39.22%20AM.png)
