### ISSUE TITLE
Better mobile views

### ISSUE THREAD

**Issue by qguv** [larvalabs/pullup#358]
While some parts of the website are optimized, certain portions (viz. the new homepage in [portrait][1] and [landscape][2]) are unviewable. Both of these have scaling issues with the buttons in the bottom, and both of these have large blank areas on-screen.

[1]: http://i.imgur.com/TZTBjsi.jpg
[2]: http://i.imgur.com/dT3pmAP.jpg

**Comment by rickhanlonii** [comment]
Going to close since that homepage doesn't exist anymore.
