### ISSUE TITLE
Consider having a goal to focus on.

### ISSUE THREAD

**Issue by howardroark** [larvalabs/pullup#359]
I think the original idea behind this project was really great. The pull request feature attracted developers who thought it was a fun idea and wanted to jump into a community to figure something out.  Making the project a clone of Hacker News or Reddit was a natural plan.  It is doubtful that things will evolve past that point, as those platforms are what people want out of the internet today. Instead focus on why platforms like Reddit and Hacker News are successful and what people really want from them.

Why not see if this project can become an attempt to distill a solid API strategy for user generated content aggregation communities. The strategy could focus on having a robust RESTful service (or something non-blocking) to offer the data and a static site generated front-end to use it.  Focus on storing the data with well considered common formats and leverage the advantages of NoSQL databases. The data should the able to scale and mix with ease. Try to use the most economically friendly tools to ensure a wide pool of contributors.  Tools like Node.js, MongoDB, Elasticsearch could enable a solid service. Ensure the project has strategies for easy automation and developer operations processes. Also have a plan for individuals to make use of cloud infrastructure automatically.  Tools like Vagrant, Salt and Docker could enable deployment and automation systems. 

It would also be worth while to build standard clients with PhoneGap and force the project to focus on common formats and decentralization.  The default clients could be both App and web based and ensure the ability to feed from any installed service.

This project could be a community of people who are using the system to create their own unique communities.  The core community could use the project's bleeding edge state to discuss its future.  Who knows, it could lead to Hacker News or Reddit learning a few things.  Certainly there is a lot to learn from those projects.  A project goal like this could benefit a lot of democratic efforts.

**Comment by rickhanlonii** [comment]
@megamattron I think this can be closed in favor of #367.

**Comment by megamattron** [comment]
@rickhanlonii Agreed, thanks.
