### ISSUE TITLE
Justify GitHub Auth permission to read/write my repositories

### ISSUE THREAD

**Issue by roryokane** [larvalabs/pullup#366]
**In short:** the reason for these permissions should be explained somewhere, to reassure users that the site will not abuse them.

I just tried to log in to Pullup after being away for a long time. I was faced with this screen:

![Pullup – GitHub login – Modify authorization](https://cloud.githubusercontent.com/assets/79168/4330780/26749a1c-3fb6-11e4-819f-85a1247c5987.png)

That is a scarily large amount of permissions the site is asking for, and I can’t imagine why a discussion forum needs it off the top of my head. If any contributor ever slipped a malicious commit in, then this site could delete the code of all my public repositories, or fill my wiki pages with rubbish, or whatever.

I looked for an explanation for this requirement on the [home page](http://pullup.io/) and the [About page](http://pullup.io/about) and its FAQ, but didn’t see any. I also searched the code and the commit history for things that explained this change, but nothing was obviously relevant.

If Pullup showed me an explanation for the permissions, I would probably accept the permissions. A good place for such an explanation would be on the [About page](http://pullup.io/about). Even better would be on a transition page after you click “Login”, but I think that’s infeasible, because the site wouldn’t be able to tell who had already given that authorization and who had not before they logged in.

If anybody knows the reason for these permissions, just putting them in a comment on this issue would be helpful, if updating the About page sounds like too much work.

**Comment by rickhanlonii** [comment]
@josephwegner @megamattron any idea why we're requiring these permissions?

**Comment by josephwegner** [comment]
I'm fairly certain that when Pulluo was originally written, Github only had
one permissions level.

That is no longer the case, so we can probably lighten the requirements.

**Comment by rickhanlonii** [comment]
That would explain it. Looks like we're requesting the `public_repo` scope [here](https://github.com/larvalabs/pullup/blob/bd4e6993e408f2ad68c8c44584f2099d33be868f/config/secrets.js#L20), which [requires](https://developer.github.com/v3/oauth/#scopes):

> Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.

**Comment by rickhanlonii** [comment]
We only need `user:email`. I've removed `public_repo` from the scopes in #384.
