### ISSUE TITLE
Autocomplete username in comments

### ISSUE THREAD

**Issue by treygriffith** [larvalabs/pullup#373]
When a user starts typing an `@`, it would be nice if it started autocompleting usernames (a la GitHub), in order to make the functionality in #372 more useful.

**Comment by rickhanlonii** [comment]
+1. The way I've done this in the past is via ElasticSearch. Any alternatives or does this require adding a new backend service?

**Comment by megamattron** [comment]
We have so few users, we could probably just keep the entire userlist in memory and search it. :)

**Comment by rickhanlonii** [comment]
touché
