### ISSUE TITLE
Update README.md: no need to include quotes around env variables when exporting them

### ISSUE THREAD

**Issue by arminkhoshbin** [larvalabs/pullup#375]
Hey,
So after following the read me file to setup my local pullup I was getting errors that "OAuth2Strategy requires a clientID option" even though I have already set my secret and clientID for github. Then I realise that there was no need for quotes around env variables. So I have gone ahead and submitted a pull request with updated version of readme file.

**Comment by rickhanlonii** [comment]
Thanks @arminkhoshbin!
