### ISSUE TITLE
[LINKS] Domain not parsed on this submission

### ISSUE THREAD

**Issue by rickhanlonii** [larvalabs/pullup#388]
## Overview

The domain on [this post](http://pullup.io/news/55cb825162b1650a00cebd9f) is empty on both the home page and on the post page itself.
#### Homepage

![](http://dp.hanlon.io/1s412V3z150C/Image%202016-03-03%20at%203.49.48%20AM.png)
#### Post page

> submitted 6 months ago from by

![](http://dp.hanlon.io/3q1R3F2i0m0s/Image%202016-03-03%20at%203.47.24%20AM.png)

**Comment by SujiRoselet** [comment]
i would like to work on this
