### ISSUE TITLE
Add margin between error message and join alert

### ISSUE THREAD

**Issue by rickhanlonii** [larvalabs/pullup#401]
## Overview

When both the flash error message and join alert are visible, there's no margin between them.
## Reproduce
1. Logout
2. Clear cookies (if you don't see the Join alert)
3. Upvote an item
## Screen

![](http://dp.hanlon.io/3k0T323t0x1R/Image%202016-03-22%20at%203.37.35%20PM.png)

**Comment by riktimmondal** [comment]
Is this project is still running on heroku??If yes then i will contribute to it as soon as possible

**Comment by robsonpf** [comment]
Hey if this resolve let me know, if not I like to work on it if is possible.
