### ISSUE TITLE
Submit News button is misaligned

### ISSUE THREAD

**Issue by rickhanlonii** [larvalabs/pullup#404]
## Overview

Some recent change has misaligned the Submit News button (must be logged in).
## Screen

![](http://dp.hanlon.io/1M0Z3t2x0q17/Image%202016-03-31%20at%2011.44.53%20AM.png)

**Comment by M-ZubairAhmed** [comment]
can i work on this?

**Comment by ppatel221** [comment]
Looks like its still open. Am i able to take this over?

**Comment by megamattron** [comment]
Sure, but the site isn't really up anymore...
